name: Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - development
      - main
    paths-ignore:
      - '**.md'
    types:
      - opened
      - synchronize

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'push' ||
      (
        github.event_name == 'pull_request' &&
        (
          startsWith(github.head_ref, 'feature/') && github.base_ref == 'development' ||
          github.head_ref == 'development' && github.base_ref == 'main'
        )
      )

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Run tests
        run: go test ./...
